# Generated by Django 5.1.5 on 2025-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='AccountHolderName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='BankAccountNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='IFSCCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
