# Generated by Django 5.1.5 on 2025-02-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='BusinessAddress',
            new_name='businessaddress',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='BusinessName',
            new_name='businessname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='City',
            new_name='city',
        ),
    ]
