# Generated by Django 5.1.5 on 2025-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='The estimated delivery date.', null=True),
        ),
    ]
