# Generated by Django 5.1.5 on 2025-01-31 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_bankdetails_accountholdername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role': 'seller_owner'}, on_delete=django.db.models.deletion.CASCADE, to='ecom.user'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'seller_owner'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ROLE_CUSTOMER', 'Customer'), ('seller_owner', 'Seller Owner'), ('ROLE_ADMIN', 'Admin')], max_length=21),
        ),
    ]
