# Generated by Django 5.1.5 on 2025-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return', 'Return')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready_to_ship', 'Ready_To_Ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('Completed', 'Completed'), ('cancelled', 'Cancelled'), ('return', 'Return')], default='pending', max_length=15),
        ),
    ]
