# Generated by Django 5.1.5 on 2025-02-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
