# Generated by Django 5.1.5 on 2025-01-25 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankAccountNo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Bank Account Number')),
                ('IFSCCode', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='IFSC Code')),
                ('AccountHolderName', models.CharField(max_length=100, verbose_name='Account Holder Name')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
                'ordering': ['AccountHolderName'],
            },
        ),
        migrations.CreateModel(
            name='ShipAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(max_length=255)),
                ('BusinessAddress', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
