# Generated by Django 5.1.5 on 2025-01-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_bankdetails_shipaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipAddress',
            new_name='ShippingAddress',
        ),
    ]
