# Generated by Django 5.1.5 on 2025-01-25 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_rename_shipaddress_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ROLE_SELLER_OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.user'),
        ),
    ]
