# Generated by Django 5.1.5 on 2025-01-27 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_shippingaddress_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dispatch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
