# Generated by Django 5.1.5 on 2025-01-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_product_dispatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dispatch_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dispatch_date',
            field=models.DateField(blank=True, help_text='The date the item was dispatched.', null=True),
        ),
    ]
