# Generated by Django 5.1.5 on 2025-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_product_dispatch_date_orderitem_dispatch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('ready_to_ship', 'Ready to Ship')], default='pending', max_length=20),
        ),
    ]
